create table if not exists drinks(
	drink_id int primary key generated by default as identity,
	drink_name varchar(35) not null unique
);

create table if not exists recipes(
	recipe_id int primary key generated by default as identity,
	recipe_desc varchar(150) not null,
	recipe_drink_id int unique,
	foreign key (recipe_drink_id) references drinks(drink_id)
);

create table if not exists inventories(
	inv_id int primary key generated by default as identity,
	inv_name varchar(10) not null unique,
	inv_num int not null,
	inv_unit varchar(3) not null
);

create table if not exists recipe_inventory(
	ri_id int primary key generated by default as identity,
	ri_recipe_id int,
	ri_invent_id int,
	ri_num int,
	foreign key (ri_recipe_id) references recipes(recipe_id),
	foreign key (ri_invent_id) references inventories(inv_id)
);

create table if not exists orders(
	order_id int primary key generated by default as identity,
	o_drink_id int,
	o_quantity int not null,
	o_date date not null,
	foreign key(o_drink_id) references drinks(drink_id)
);

create table if not exists statistics(
	stat_id int primary key generated by default as identity,
	stat_drink_id int,
	stat_quantity int not null,
	stat_start_date date not null,
	foreign key (stat_drink_id) references drinks(drink_id)
);